name: Docker Image CI

on: 
  workflow_dispatch:
    inputs:
      suite:
        description: 'Ubuntu Suite'     
        required: true
        default: 'noble'
      version:
        description: 'GCC Version'
        required: true
        default: '13.2.0'

jobs:
  build:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - runner: ubuntu-22.04
            platform: linux/amd64
            suffix: amd64
          - runner: ubuntu-22.04-arm
            platform: linux/arm64
            suffix: arm64
    name: build-${{ github.event.inputs.version }}-${{ github.event.inputs.suite }}-${{ matrix.suffix }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Generate Dockerfile
      run: ./update.sh ${{ github.event.inputs.suite }} ${{ github.event.inputs.version }}
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./${{ github.event.inputs.version }}-Dockerfile.tmp
        platforms: ${{ matrix.platform }}
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/gcc:${{ github.event.inputs.version }}-${{ github.event.inputs.suite }}-${{ matrix.suffix }}
